sudo: required
services:
  - docker
before_install:
  - docker build -t empulseglobal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true empulseglobal/docker-react npm run test -- --coverage --watchAll=false
